### PR TITLE
Fix missing import rename to identify permissions

### PR DESCRIPTION
**Pull request by jpreynat**
When using `firemin@0.3.1` with `firetree@0.1.5`, the process fails with the following error:
```
Error: Expected operator ':'. Instead found [object Object]
    at expectColonOperator (/Users/jpreynat/GitBook/gitbook-x/node_modules/firetree/src/parser/pipes/expectColonOperator.js:10:4)
    at /Users/jpreynat/GitBook/gitbook-x/node_modules/ramda/src/internal/_pipe.js:3:14
    at /Users/jpreynat/GitBook/gitbook-x/node_modules/ramda/src/internal/_pipe.js:3:27
    at /Users/jpreynat/GitBook/gitbook-x/node_modules/ramda/src/internal/_pipe.js:3:27
    at identifyAllowStatementChildren (/Users/jpreynat/GitBook/gitbook-x/node_modules/ramda/src/internal/_arity.js:11:19)
    at Object.identify (/Users/jpreynat/GitBook/gitbook-x/node_modules/firetree/src/parser/nodes/AllowStatement.js:40:10)
    at Object.identify (/Users/jpreynat/GitBook/gitbook-x/node_modules/firetree/src/parser/nodes/Statement.js:13:17)
    at /Users/jpreynat/GitBook/gitbook-x/node_modules/firetree/src/ast/identifyNode.js:10:21
    at /Users/jpreynat/GitBook/gitbook-x/node_modules/ramda/src/internal/_curryN.js:46:27
    at /Users/jpreynat/GitBook/gitbook-x/node_modules/ramda/src/internal/_arity.js:11:19
```

This PR fixes a small forgotten update of the import filename to identify allow statements with multiple permissions from https://github.com/brianneisler/firetree/pull/11

### CODE REVIEW

**Comment by brianneisler** [comment]
Great catch @jpreynat! Thanks for the PR!

**Comment by jpreynat** [comment]
You're most welcome @brianneisler 👌

**Comment by brianneisler** [comment]
@jpreynat just a heads up, I plan on writing a couple tests to cover this and then releasing a new version this weekend.

**Comment by jpreynat** [comment]
@brianneisler Cool, thanks for the heads up 👍 
I tried to add some tests but couldn't figure out where was the right place and methods to call to do so.

**Pull request merged**
